Repository COSC481W-2020Fall/cosc481w-581-2020-fall-datatitans, pull requests merged in 2020-09, with the labels that each got.

#5 4 Regenerate Django files
  datatitan_site/datatitan_site/asgi.py
  datatitan_site/datatitan_site/settings.py
  datatitan_site/datatitan_site/urls.py
  datatitan_site/datatitan_site/wsgi.py
  datatitan_site/manage.py
Labels: enhancement

#7 updated README with HTML info
  README.md
Labels: documentation

#10 This commit updates the Python Version in the README file.
  README.md
Labels: documentation

#11 9 Out-of-date Python version listed in README
  README.md
Labels: documentation

#16 Update requirements.txt
  requirements.txt
Labels: documentation

#18 add country model
  datatitan_site/data/__init__.py
  datatitan_site/data/admin.py
  datatitan_site/data/apps.py
  datatitan_site/data/migrations/__init__.py
  datatitan_site/data/models.py
  datatitan_site/data/tests.py
  datatitan_site/data/views.py
  datatitan_site/datatitan_site/settings.py
Labels: enhancement

#20 Updated Pipfile and README
  Pipfile
  Pipfile.lock
  README.md
Labels: documentation

#53 Implemented automatic file updates, and auto-generation of database
  .idea/DataTitans.iml
  .idea/dataSources.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  .idea/other.xml
  .idea/rSettings.xml
  .idea/sqldialects.xml
  README.md
  UseCaseDiagram.png
  datatitan_site/data/database/.gitignore
  datatitan_site/data/database_handler.py
  datatitan_site/data/input/.gitignore
  datatitan_site/data/migrations/0004_coviddataclean.py
  datatitan_site/data/models.py
  datatitan_site/data/urls.py
  datatitan_site/data/views.py
  datatitan_site/datatitan_site/urls.py
  datatitan_site/images/adminPage.png
  datatitan_site/images/blog.png
Labels: documentation, enhancement

#61 60 Install Coverage and Pytest
  Pipfile
  Pipfile.lock
Labels: enhancement

#62 59 unstable file paths used in scripts
  datatitan_site/data/scripts/CreateChart.py
  datatitan_site/temp/TestPaths.py
  datatitan_site/temp/testPlots.py
Labels: bug

#65 Implemented automatic regeneration of SQLite database on startup
  .idea/other.xml
  datatitan_site/data/database_handler.py
  datatitan_site/data/migrations/0005_auto_20200920_1607.py
  datatitan_site/data/migrations/0006_auto_20200920_1826.py
  datatitan_site/data/migrations/0007_coviddataraw_new_tests_smoothed.py
  datatitan_site/data/migrations/0008_coviddataraw_new_tests_smoothed_per_thousand.py
  datatitan_site/data/migrations/0009_auto_20200920_1908.py
  datatitan_site/data/migrations/0010_auto_20200920_1913.py
  datatitan_site/data/models.py
  datatitan_site/data/urls.py
Labels: enhancement

#76 Fixed startup
  datatitan_site/data/apps.py
  datatitan_site/data/database_handler.py
  datatitan_site/data/migrations/0001_initial.py
  datatitan_site/data/migrations/0002_auto_20200921_2016.py
  datatitan_site/data/migrations/0002_post.py
  datatitan_site/data/migrations/0003_auto_20200916_1555.py
  datatitan_site/data/migrations/0003_auto_20200921_2018.py
  datatitan_site/data/migrations/0004_coviddataclean.py
  datatitan_site/data/migrations/0004_remove_coviddataclean_new_cases.py
  datatitan_site/data/migrations/0005_auto_20200920_1607.py
  datatitan_site/data/migrations/0005_coviddataclean_new_cases.py
  datatitan_site/data/migrations/0006_auto_20200920_1826.py
  datatitan_site/data/migrations/0006_auto_20200921_2103.py
  datatitan_site/data/migrations/0007_auto_20200922_1720.py
  datatitan_site/data/migrations/0007_coviddataraw_new_tests_smoothed.py
  datatitan_site/data/migrations/0008_coviddataraw_new_tests_smoothed_per_thousand.py
  datatitan_site/data/migrations/0009_auto_20200920_1908.py
  datatitan_site/data/migrations/0010_auto_20200920_1913.py
  datatitan_site/data/models.py
  datatitan_site/data/urls.py
  datatitan_site/temp/PrototypeGraphSetup.py
Labels: bug

#78 Completed cleaned up table
  datatitan_site/data/database_handler.py
  datatitan_site/data/migrations/0008_auto_20200922_1845.py
  datatitan_site/data/models.py
Labels: bug

#80 Improved file logic of views.py
  datatitan_site/data/migrations/0009_auto_20200922_1919.py
  datatitan_site/data/models.py
  datatitan_site/data/views.py
  datatitan_site/temp/PrototypeGraphSetup.py
Labels: enhancement

#84 Updated README file
  README.md
  datatitan_site/data/static/.gitignore
Labels: documentation

#87 85 change data retrieval request to get
  datatitan_site/data/models.py
  datatitan_site/data/scripts/generate_graphs.py
  datatitan_site/data/templates/data.html
  datatitan_site/data/views.py
Labels: enhancement
